# name: Deploy node application
# permissions:
#   actions: write       # Necessary to cancel workflow executions
#   checks: write        # Necessary to write reports
#   pull-requests: write # Necessary to comment on PRs
#   contents: read
#   packages: write
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Source
#         uses: action/checkout@v2
#         with:
#           repository: Madurad/jenkinsfiles
#           token: ${{ secrets.PAT }}
#           ref: master
#       - name: Login to docker hub
#         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build Docker Image
#         run: docker build -t kavinprasanth/nodejs .
#       - name: Publish Image to docker hub
#         run: docker push kavinprasanth/nodejs:latest
#   deploy:
#     needs: build
#     runs-on: self-hosted
#     steps:
#       - name: Pull Image From the docker hub
#         run: docker pull kavinprasanth/nodejs:latest
#       - name: Run Docker Container
#         run: run docker -d  -p 5000:5000 --name nodejs-app-container -e  MONGO_PASSWORD='{{ secrets.MONGO_PASSWORD }}' kavinprasanth/nodejs

# This is a basic workflow to help you get started with Actions

name: Deploy node application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t kavinprasanth/nodejs .
      - name: Publish Image to docker hub
        run: docker push kavinprasanth/nodejs:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: Pull Image From the docker hub
        run: docker pull kavinprasanth/nodejs:latest
      - name: Run Docker Container
        run: run docker -d  -p 5000:5000 --name nodejs-app-container -e  MONGO_PASSWORD='{{ secrets.MONGO_PASSWORD }}' kavinprasanth/nodejs
