# Author: kavin
name: Deploy node application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: sudo docker build -t kavinprasanth/nodejs .
      - name: Publish Image to docker hub
        run: sudo docker push kavinprasanth/nodejs:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image From the docker hub
        run: sudo docker pull kavinprasanth/nodejs:latest
      - name: Run Docker Container
        run: sudo docker run -d  -p 8080:5000 --name nodejs-container -e  MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} kavinprasanth/nodejs
