name: Deploy node application
permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: action/checkout@v2
        with:
          repository: Madurad/jenkinsfiles
          token: ${{ secrets.PAT }}
          ref: master
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t kavinprasanth/nodejs .
      - name: Publish Image to docker hub
        run: docker push kavinprasanth/nodejs:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image From the docker hub
        run: docker pull kavinprasanth/nodejs:latest
      - name: Run Docker Container
        run: run docker -d  -p 5000:5000 --name nodejs-app-container -e  MONGO_PASSWORD='{{ secrets.MONGO_PASSWORD }}' kavinprasanth/nodejs
